name: Global routes monthly dump

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # runs on the 1st of every month

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AERODATABOX_API_KEY: ${{ secrets.AERODATABOX_API_KEY }}
      AERODATABOX_API_HOST: ${{ secrets.AERODATABOX_API_HOST }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Sanity check to confirm vendor CSV exists
      - name: Sanity check vendor CSV
        run: |
          echo "PWD: $(pwd)"
          ls -lah
          echo "---"
          ls -lah data || true
          echo "---"
          ls -lah data/vendor || true
          echo "--- head of vendor csv ---"
          head -n 10 data/vendor/megabus.csv || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests ftfy

      - name: Build monthly dump (Air + Bus)
        run: |
          echo "🚌✈️ Building combined bus + air dataset..."
          mkdir -p data/outputs
          PYTHONPATH=$GITHUB_WORKSPACE python -m scripts.build_monthly --out data/outputs
          
      - name: Commit CSV to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin main
          git reset --soft origin/main
          git add data/outputs/world_bus.csv
          git commit -m "Monthly global routes update [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main || true
          git push origin main || true

      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: world-routes
          path: data/outputs/world_bus.csv
