name: Global Bus Data Dump

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 1 * *"  # runs monthly at 06:00 UTC on the 1st

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pandas requests python-dateutil ftfy

      - name: Build monthly dump
        run: |
          mkdir -p data/outputs
          PYTHONPATH=$GITHUB_WORKSPACE python -m scripts.build_monthly --out data/outputs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: world-bus-routes
          path: data/outputs/*.csv
