name: Global Bus Data Dump

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 1 * *"   # runs monthly at 06:00 UTC on the 1st of every month
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pandas requests python-dateutil ftfy

      - name: Build monthly dump
        run: |
          mkdir -p data/outputs
          PYTHONPATH=$GITHUB_WORKSPACE python -m scripts.build_monthly --out data/outputs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: world-bus-routes
          path: data/outputs/*.csv

      # 👇 This is the *new* part that pushes the file into your repo
      - name: Commit CSV to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/outputs/world_bus.csv
          git commit -m "Monthly bus routes update [skip ci]" || echo "No changes to commit"
          git push
