name: Global bus data dump

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pandas requests

      - name: Build monthly dump
        run: |
          PYTHONPATH=$GITHUB_WORKSPACE python -m scripts.build_monthly --out data/outputs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: world-bus-routes
          path: data/outputs/world_bus.csv
