  import os
import pandas as pd

# --- Import all bus connectors ---
from connectors import (
    bus_flixbus,
    bus_alsa,
    bus_avanza,
    bus_nationalexpress,
    bus_blablabus,
    bus_megabus,
    bus_irishcitylink,
)

def main(out_dir="data/outputs"):
    print("🚌 Building global bus dataset...")

    frames = []
    connectors = [
        ("FlixBus", bus_flixbus),
        ("ALSA", bus_alsa),
        ("Avanza", bus_avanza),
        ("National Express", bus_nationalexpress),
        ("BlaBlaBus", bus_blablabus),
        ("Megabus UK", bus_megabus),
        ("Irish Citylink", bus_irishcitylink),
    ]

    # --- Run all connectors one by one ---
    for name, module in connectors:
        try:
            print(f"\n▶ Fetching {name} routes...")
            df = module.fetch_routes()
            if not df.empty:
                print(f"✅ {name}: {len(df):,} routes loaded")
                frames.append(df)
            else:
                print(f"⚠️ {name}: no data returned")
        except Exception as e:
            print(f"❌ Failed to fetch {name}: {e}")

    # --- Combine and save ---
    if not frames:
        print("❌ No data retrieved from any connector.")
        return

    combined = pd.concat(frames, ignore_index=True).drop_duplicates()
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "world_bus.csv")
    combined.to_csv(out_path, index=False, encoding="utf-8")

    print(f"\n✅ Successfully saved {len(combined):,} total routes to {out_path}")
    print(f"Operators included: {', '.join([n for n, _ in connectors])}")

if __name__ == "__main__":
    main()
