import os
import pandas as pd
from connectors import (
    bus_flixbus,
    bus_alsa,
    bus_avanza,
    bus_nationalexpress,
    bus_blablabus,
    bus_megabus,
    bus_irishcitylink,
)

def main(out_dir="data/outputs"):
    print("Building global bus dataset...")

    frames = []
    connectors = [
        bus_flixbus,
        bus_alsa,
        bus_avanza,
        bus_nationalexpress,
        bus_blablabus,
        bus_megabus,
        bus_irishcitylink,
    ]

    for c in connectors:
        try:
            df = c.fetch_routes()
            if not df.empty:
                frames.append(df)
        except Exception as e:
            print(f"Failed {c.__name__}: {e}")

    if not frames:
        print("No data retrieved.")
        return

    all_df = pd.concat(frames, ignore_index=True).drop_duplicates()
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "world_bus.csv")
    all_df.to_csv(out_path, index=False)
    print(f"✅ Saved {len(all_df):,} combined bus routes to {out_path}")

if __name__ == "__main__":
    main()
