name: Global bus data dump

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # runs on the 1st of every month

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Sanity check to confirm vendor CSV exists
      - name: Sanity check vendor CSV
        run: |
          echo "PWD: $(pwd)"
          ls -lah
          echo "---"
          ls -lah data || true
          echo "---"
          ls -lah data/vendor || true
          echo "--- head of vendor csv ---"
          head -n 10 data/vendor/megabus.csv || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Build monthly dump
        run: |
          mkdir -p data/outputs
          PYTHONPATH=$GITHUB_WORKSPACE python -m scripts.build_monthly --out data/outputs

      - name: Commit CSV to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/outputs/world_bus.csv
          git commit -m "Monthly bus routes update [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
